### ISSUE TITLE
How much would Upstra SDK impact on overall app size

### ISSUE THREAD

**Issue by touchaponk** [EkoCommunications/Upstra-Q-A#1]
If an app size is originally 10MB - what would be the size of the app (ipa file) after we included Upstra SDK in

**Comment by stevenwangamity** [comment]
@trustratch @nRewik Could you please summarize the findings for both Android & iOS, thanks

**Comment by nRewik** [comment]
Here is the size report after export to .ipa.
- EkoChat.framework ~1mb
- Realm.framework ~1mb
- UpstraUIKit.framework ~2mb

[sdk-size-report.txt](https://github.com/EkoCommunications/Upstra-Q-A/files/5658590/sdk-size-report.txt)
