### ISSUE TITLE
Exporting list of members from a particular channel within the admin panel to a google sheet/excel

### ISSUE THREAD

**Issue by MelissaLim-airasia** [EkoCommunications/Upstra-Q-A#10]
Hi there, is there a way to export the list of members conveniently from the admin panel? Thanks.

**Comment by stevenwangamity** [comment]
@MelissaLim-airasia , exporting from admin panel is currently not supported

**Comment by MelissaLim-airasia** [comment]
Thanks Steven. Is there an alternate solution to extracting the existing user list of a particular channel? Reason being, we would like to make quick comparisons among channels to identify common users during certain behavioral experiments.

**Comment by stevenwangamity** [comment]
@MelissaLim-airasia Unfortunately as far as I can see here in light of admin panel's capabilities
1. copy and paste from the UI (some channels have plenty of users so it requires a good amount of manual work)
2. Request to Amity which requires engineering team to pull from database, but it will go to the standard sprint planning and will take longer time

**Comment by MelissaLim-airasia** [comment]
Understood. Thanks.
