### ISSUE TITLE
Can we mute a specific broadcasted message towards a channel?

### ISSUE THREAD

**Issue by MelissaLim-airasia** [EkoCommunications/Upstra-Q-A#12]
For instance, in the case where we intend to broadcast several push messages within the same day, across multiple channels and public community chat rooms, the concern is that the same user (following more than 1 channel and chat rooms) will be receiving multiple push notifications on their phones.

That said, we would like to see if there's a way to mute selected messages that we intend to broadcast within the community chat rooms instead. With that, some messages would not need to be linked to a notification and can just be broadcasted within the chat screen (if needed). We note that users can mute these channnels themselves but would like to check if there's an alternative within the admin panel.

Is there a function for such situations?

**Comment by stevenwangamity** [comment]
@MelissaLim-airasia I think the ask here is whether we support a message level setting to be able to send a message without a push. Unfortunately it's not supported as of now

**Comment by MelissaLim-airasia** [comment]
Noted with thanks. Are there plans to have this in the future? Thank you.

**Comment by MelissaLim-airasia** [comment]
Hi Steven,
What about frequency cap or overlap visibility functions?

**Comment by stevenwangamity** [comment]
> Noted with thanks. Are there plans to have this in the future? Thank you.

No, we don't have plan to put setting on message level that's too granular. But wondering why still decide to broadcast multiple times but at the end of the day don't want users to see the pushes?

**Comment by stevenwangamity** [comment]
> Hi Steven,
> What about frequency cap or overlap visibility functions?

I think maybe the real ask here is whether there is a "batch push" function, so users will only receive one push with the summary of all received pushes?
(Unfortunately not supported as of now as well)
