### ISSUE TITLE
Generate New User on Upstra UIKit

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#15]
Is there a way to generate new users for mocking purposes? I would like to have multiple users commenting on the same post such as that.

**Comment by stevenwangamity** [comment]
@tanawateko please help check this one

**Comment by stevenwangamity** [comment]
> Is there a way to generate new users for mocking purposes? I would like to have multiple users commenting on the same post such as that.

you can simply set userid and name via SDK to create a user

**Comment by tpark-amity** [comment]
> > Is there a way to generate new users for mocking purposes? I would like to have multiple users commenting on the same post such as that.
> 
> you can simply set userid and name via SDK to create a user

I don't see that in the docs, probably missed it. Could you show me the way?

**Comment by nrlnishan** [comment]
https://docs.upstra.co/android/uikit/setup-and-authentication
https://docs.upstra.co/ios/uikit/setup-and-authentication
