### ISSUE TITLE
Adding a User to a Channel/Let the User see Chat Channels

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#16]
Is there a way to manually add a user to a channel? Or is there a way to let the user see all chat channels available on the network?

**Comment by stevenwangamity** [comment]
> Is there a way to manually add a user to a channel? Or is there a way to let the user see all chat channels available on the network?

this mentions how to manage user in a channel: https://docs.upstra.co/ios/channels#manage-members
this will you to check all the channels: https://docs.upstra.co/ios/channels#channel-query

**Comment by tpark-amity** [comment]
> > Is there a way to manually add a user to a channel? Or is there a way to let the user see all chat channels available on the network?
> 
> this mentions how to manage user in a channel: https://docs.upstra.co/ios/channels#manage-members
> this will you to check all the channels: https://docs.upstra.co/ios/channels#channel-query

Thank you for your response!
