### ISSUE TITLE
Community Search View on UIKit

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#18]
I did a custom controller that acts like a parent which takes control over the child controller (EkoCommunityHomePageViewController)'s search icon on the UIKit and now it's nowhere to be seen.

I'm trying to find a work around where I can present the search icon on the header area of the view and access the community search page. Is there a way I can do that?

**Comment by tanawateko** [comment]
Hi krub , sorry for late reply , this one is for iOS correct ? , if so , I will ask iOS engineer to respond to this

**Comment by tpark-amity** [comment]
> Hi krub , sorry for late reply , this one is for iOS correct ? , if so , I will ask iOS engineer to respond to this

That's correct. Yes please.

**Comment by siengnonta** [comment]
Due to the search function isn't public yet, please follow this instruction for implementing community search.
https://docs.upstra.co/ios/community#community-query
