### ISSUE TITLE
A user is a member of a channel but no channel are listed on EkoChatHomePageViewController

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#19]
I assume that for a chat channel to come up, the user needs to be a member of that channel first. I added the user to the channel but the channel is still not listed on EkoChatHomePageViewController. The channel type is a standard.

**Comment by iamsnowz** [comment]
Sorry for the late reply. we only support the channel type is `Conversation` for now.

**Comment by tpark-amity** [comment]
> Sorry for the late reply. we only support the channel type is `Conversation` for now.

There is no channel type "Conversation" on the admin panel for creation. Does it mean I have to call an API to create this channel type only?
