### ISSUE TITLE
How to add custom action / view in EkoMessageListViewController?

### ISSUE THREAD

**Issue by stevenwangamity** [EkoCommunications/Upstra-Q-A#2]
Question from vodworks

Since we have to add a custom message in the chat screen, we have tried setting a custom nib to EKOMessageListViewController but it's not working on sdk. How can we assign our custom view to EKOMessageListViewController table view? Is there any way to receive a user Interaction(Tap) event/delegate to perform custom action?

**Comment by siengnonta** [comment]
There is an API for custom cells but the view assigning isn't supported yet. 
Can you give me some design references to ensure I understand your purpose correctly?

**Comment by tpark-amity** [comment]
Response from Vodworks:

"Below is the design we want to add into custom messages but I tried calling custom nibs from register function it didn’t work."

![Screen Shot 2020-12-18 at 14 18 14](https://user-images.githubusercontent.com/74768384/102585959-e1141e00-413b-11eb-8032-c1775445724a.png)

**Comment by iamsnowz** [comment]
Sorry for the late reply, for the how to custom messages in lastest version you can follow the code below like this:

1. Create a new instance `EkoMessageListViewController`
`
        let messageListVC = EkoMessageListViewController.make(channelId: "ChannelID")
        messageListVC.dataSource = self
`

2. For your `ViewController` need to conform to protocol `EkoMessageListDataSource` like this:
`
ViewController: EkoMessageListDataSource {
    func cellForMessageTypes() -> [EkoMessageTypes : EkoMessageCellProtocol.Type] {
        return [
            .textIncoming: CustomMessageTextIncomingTableViewCell.self
        ]
    }
}
`
-------------------------------------------------------------------
FYI: for the custom cell need to create with a nib file example: 
`
     CustomMessageTextIncomingTableViewCell.swift
     CustomMessageTextIncomingTableViewCell.nib
`
