### ISSUE TITLE
Back button doesn't work/missing on multiple pages of the UIKit

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#20]
For context, I have made a custom controller and pass in the view controller from the UIKit as child controllers.

The back button is not to be seen anywhere on multiple pages of the view controller, is there a way to bring that functionality back?
Example:
![8f66186d0601](https://user-images.githubusercontent.com/74768384/103504462-0c13a700-4e8a-11eb-9e9e-b43756c3b097.jpeg)
![409f4694e695](https://user-images.githubusercontent.com/74768384/103504464-0d44d400-4e8a-11eb-826d-770f5bc84427.jpeg)
![547a74bd1d60](https://user-images.githubusercontent.com/74768384/103504470-0fa72e00-4e8a-11eb-85e9-a9d3593a2d1d.jpeg)

**In addition, the back button here is presented but the functionality of it doesn't work. Can you please advise?**
![6dc835605956](https://user-images.githubusercontent.com/74768384/103504509-38c7be80-4e8a-11eb-9230-6858554e36f9.jpeg)

Thank you!

**Comment by tpark-amity** [comment]
Additional information on what might cause the issue after some investigation for the back button issue on creating a new post screen.

On tap of a new post, SDK is presenting the screen and on the next screen, since the navigation bar is being used, it tries to pop a controller on the back button pressed which is not working.
1- you have to push the screen for a new post
2- get custom action and dismiss controller instead of pop.

**Comment by siengnonta** [comment]
View controllers in Upstra SDK are subclassing from EkoViewController. Each contains `EkoNavigationBarType`, enums to determine navigation type. 
The navigation bar type requires UINavigationController to make it works. See the example below.

**1. Presenting**
If you want to present Upstra view contorllers, please create navigation controller once before presenting.
```swift
class YourHomeViewController: UIViewController {
    func presentPostTarget() {
        let vc = EkoPostTargetSelectionViewController.make()
        let navigationController = UINavigationController(rootViewController: vc)
        present(nvc, animated: true, completion: nil)
    }
}
```
**2. Pushing**
If you don't have UINavigationController in your view hierarchy yet, create it once.
```swift

class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        let home = YourHomeViewController()
        UIApplication.shared.windows.first?.rootViewController = UINavigationController(rootViewController: home)
        UIApplication.shared.windows.first?.makeKeyAndVisible()
        
        return true
    }
}
```

In case you already have a navigation controller, just push it simply and please ensure `viewController.hidesBottomBarWhenPushed` is false.
```swift
class YourHomeViewController: UIViewController {
    func pushPostTarget() {
       let vc = EkoPostTargetSelectionViewController.make()
        navigationController?.pushViewController(vc, animated: true) // please check if navigationController is not nil
    }
}
```
