### ISSUE TITLE
User unable to join a channel

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#3]
**Describe the bug**
Vodworks have been trying to use the SDK to have a user join a specific channel that they have created. However, the SDK does not return anything, not even an error message. 

**To Reproduce**
Below are the codes that they have used in their attempt to make a user join a specific channel.
![Screen Shot 2020-12-09 at 15 50 37](https://user-images.githubusercontent.com/74768384/101606741-4b3f0b80-3a36-11eb-9500-5f50d2f582bb.png)

**Expected behavior**
The SDK should be able to add a user to a specific channel.

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: iOS 13
 - Using iOS SDK as per docs: https://docs.upstra.co/ios/start
 - Upstra UI Kit Version: 1.5.3

**Comment by stevenwangamity** [comment]
@nRewik please have a check

**Comment by siengnonta** [comment]
When calling `observe(:_)` there will be a return value `EkoNotificationToken`. This token needs to be declared globally to keep its reference.

```swift
// global scope
var globalChannelToken: EkoNotificationToken?
var channelToken: EkoNotificationToken?

func setup() {
   globalChannelToken = globalChannel.observe { // assign to a token to keep reference of this observation
       ...
   }

   channelToken = globalChannel.observe { 
       ...
   }
}
```

**Comment by nRewik** [comment]
May be relates to this issue https://github.com/EkoCommunications/Upstra-Q-A/issues/7 ?

The SDK uses [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) pattern.

The observe block will be notified, as long as the token is held. If you want to unobserve, deallocate the token.

This is similar to the approach of observer API in iOS.

- https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver
- https://developer.apple.com/documentation/swift/cocoa_design_patterns/using_key-value_observing_in_swift

**Comment by nRewik** [comment]
Close this, please re-open if the issue still happen.
