### ISSUE TITLE
Error while upgrading UpstraUIKit from 1.5.3 to 1.6.0

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#4]
I have recommended Vodworks to upgrade to our latest version of the UIKit SDK for stability and features that they required for the demo. So far, they have a problem upgrading the UIKit version from 1.5.3 to 1.6.0

What they have run: pod install --repo-update
Error messages: https://pastebin.com/ZFB8iYGW

What should they do to resolve this issue? Apologize for the limited information provided here. Please assist ASAP.

**Comment by stevenwangamity** [comment]
@tanawateko please help check on UIKit side

**Comment by nRewik** [comment]
Could you try update/reinstall CocoaPods binary?

We have checked it. Upgrading the SDK via pod works fine on our machine.

![406efcee64a4462cbdf72a3d38ade6e4](https://user-images.githubusercontent.com/6581089/102169707-617d1980-3ec5-11eb-9ef8-0b8539e55a92.png)

Here is the [Podfile](https://github.com/EkoCommunications/Upstra-Q-A/files/5693474/Podfile.txt) that we test.

--------

Alternatively you can download `.xcframework` and link it manually.

https://github.com/EkoCommunications/EkoMessagingSDKUIKit/releases

**Comment by nRewik** [comment]
Close this, please re-open if the issue still happen.
