### ISSUE TITLE
Unable to create post using EkoTextPostBuilder()

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#7]
**Describe the bug**
Vodworks is trying to use the Upstra SDK to create a post so that they can further create comments on that post. The current situation is that they do not receive any callback once the function is called and the post is not created as well.

**To Reproduce**
Below is the code that they use to implement this:
![Screen Shot 2020-12-10 at 15 25 24](https://user-images.githubusercontent.com/74768384/101740849-f06fe780-3afb-11eb-94f2-3f8a389ff24e.png)

**Expected behavior**
Vodworks should be able to create posts on the Upstra SDK.

**Smartphone (please complete the following information):**
 - OS: iOS 13
 - SDK Version: Latest as per the get started doc here: https://docs.upstra.co/ios/start

**Comment by stevenwangamity** [comment]
@nRewik

**Comment by siengnonta** [comment]
Seems like this issue relates to object references. Can you please try moving `feedRepository` to the global scope and run it once again?

**Comment by nRewik** [comment]
The repository should be held in the scope that we intend to make it run.

If we create the repository in the function scope, the instance will be deallocate after it is out of scope.

```swift
func someWhere() {
     let feedRepostiory = ....
     // When the function ends, feedRepostiory is destroyed, it no longer run or notify anything.
}
```

You could make feed repository as the app scope variable, or another scope that prolong the lifetime of feed repository.

For example

```swift
class AppManager {
    var feedRepository: EkoFeedRepository?
}

func someWhere() {
    AppManager.shared.feedRepository.create(...., { ... })
}

```

**Comment by nRewik** [comment]
Close this, please re-open if the issue still happen.
