### ISSUE TITLE
Search icon and function is not presented on EkoCommunityHomePageController View

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#8]
Vodworks is implementing the community page by using the Upstra UIKit with EkoCommunityHomePageController. However, they are not able to find the search icon/function on the top right of the screen.

It seems so for me as well when I tried to represent the view during my own demo app development using the UIKit and the same controller. But I believe there is this function presented on the UIKit as I've seen it on the sample app, would it somehow get deleted on the current version of the UIKIT (1.6.0)?

**Comment by stevenwangamity** [comment]
@tanawateko

**Comment by siengnonta** [comment]
On version 1.6.0, the search button is still on the top right of EkoCommunityHomePageController.
This button is using base color, did you set a custom theme or other customization?

**Comment by tpark-amity** [comment]
Response from Vodworks:

"I have customized the theme according to design
. As you remember there was an issue in upstra kit when I changed tabs on EKOCmmunityhomepageController and you asked me to create a custom controller and pass Newsfeed and Explore controller as a child. So now the search icon on top is a custom button."

**Comment by siengnonta** [comment]
Due to the search function isn't public API, please follow this instruction for implementing community search.
https://docs.upstra.co/ios/community#community-query
