### ISSUE TITLE
Unable to fetch comments from EkoCommentRepository

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Upstra-Q-A#9]
Vodworks has tried to fetch comments that are posted below a post by using the postId that returns the latest comment on the post (See screenshot below for description). However, it returns no comment from the SDK. Also, the comment button apparently stopped working after posting a few comments.

Vodworks has described the issue as below:

![Screen Shot 2020-12-15 at 11 24 48](https://user-images.githubusercontent.com/74768384/102171016-27614700-3ec8-11eb-8f1a-93255d567506.png)

Please assist. Thank you.

**Comment by siengnonta** [comment]
**1. Comment fetching**
`postComments` is a collection that needs to observed once. The return value must be assigned to `postCommentsToken` for holding its reference.

Example:
```swift
class YourViewController: UIViewController { 
   var repository: EkoCommentRepository?
   var postComments: EkoCollection<EkoComment>?
   var postCommentsToken: EkoNotificationToken?
   
   ...
   
   func setup() {
      repository = EkoCommentRepository(client: client!)
      postComments = repository?.comments(withReferenceId: postId, referenceType: .post, filterByParentId: true, parentId: nil, orderBy: .descending, includeDeleted: false)
      postCommentsToken = commentCollection?.observe { collection, _, error in
         // persist data here
         print(collection.count())
   }
}
```

**Comment by siengnonta** [comment]
**2. Current user fetching**
`EkoClient` must be initialized with the correct API key. Then call `registerDevice(: _)` with user id and display name.
Can you recheck if `self.client` is not nil? If your problem isn't solved, please provide us with more context.

**3. Comment button doesn't respond**
There are 2 areas that are responsible for navigating to post detail (the page showing post, comment, and compose bar).
- comment button (on the right of post like button)
- comment cell (under the post like button)

We have tried reproducing the issue but it works fine on our side. Can you explain more on which button you tapped on?

**Comment by tpark-amity** [comment]
Vodworks informed that it has been fixed, thank you for your assistance!
